# local / prod
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tacodb?characterEncoding=UTF-8&serverTimezone=UTC
    username: sa
    password: sa

    
logging:
  level:
    tacos: WARN

#logging:
#  level:
#    org.springframework.data.rest: debug
