# local / prod
spring:

  jms:
    template:
      receive-timeout: 2
    queue:
      destination: tacocloud.order.queue

  artemis:
    mode: native
    host: localhost
    port: 61616
    user: admin
    password: secret
    embedded:
      enabled: false

  rabbitmq:
    dynamic: true
    host: localhost
    port: 5672
    username: admin
    password: secret

  kafka:
    bootstrap-servers:
      - localhost:29092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos.domain
    
logging:
  level:
    tacos: DEBUG

server:
  port: 8090

