# local / prod
spring:

  jms:
    template:
      receive-timeout: 2
    queue:
      destination: tacocloud.order.queue

  artemis:
    mode: native
    host: localhost
    port: 61616
    user: admin
    password: secret
    embedded:
      enabled: false

  rabbitmq:
    dynamic: true
    host: localhost
    port: 5672
    username: admin
    password: secret
    
logging:
  level:
    tacos: DEBUG

server:
  port: 8081

